// <auto-generated />
using System;
using Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Context.Migrations
{
    [DbContext(typeof(DiscogsContext))]
    [Migration("20200831120759_ArtistDB")]
    partial class ArtistDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DiscogsContext.Models.Alias", b =>
                {
                    b.Property<int>("ARTIST_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ARTIST_ID1")
                        .HasColumnType("int");

                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ARTIST_ID");

                    b.HasIndex("ARTIST_ID1");

                    b.ToTable("Alias");
                });

            modelBuilder.Entity("DiscogsContext.Models.Artist", b =>
                {
                    b.Property<int>("ARTIST_ID")
                        .HasColumnType("int");

                    b.Property<string>("DATA_QUALITY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameVariations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROFILE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REALNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Urls")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ARTIST_ID");

                    b.ToTable("Artist");
                });

            modelBuilder.Entity("DiscogsContext.Models.Group", b =>
                {
                    b.Property<int>("ARTIST_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ARTIST_ID1")
                        .HasColumnType("int");

                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ARTIST_ID");

                    b.HasIndex("ARTIST_ID1");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("DiscogsContext.Models.Image", b =>
                {
                    b.Property<int>("HEIGHT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ARTIST_ID")
                        .HasColumnType("int");

                    b.Property<string>("TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URI150")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WIDTH")
                        .HasColumnType("int");

                    b.HasKey("HEIGHT");

                    b.HasIndex("ARTIST_ID");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("DiscogsContext.Models.Label", b =>
                {
                    b.Property<int>("LABEL_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CONTACTINFO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DATA_QUALITY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PARENTLABELLABEL_ID")
                        .HasColumnType("int");

                    b.Property<string>("PROFILE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LABEL_ID");

                    b.HasIndex("PARENTLABELLABEL_ID");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("DiscogsContext.Models.Label+SubLabel", b =>
                {
                    b.Property<int>("LABEL_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LABEL_ID");

                    b.ToTable("SubLabel");
                });

            modelBuilder.Entity("DiscogsContext.Models.Master", b =>
                {
                    b.Property<int>("MASTER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DATA_QUALITY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MAIN_RELEASE_ID")
                        .HasColumnType("int");

                    b.Property<string>("NOTES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TITLE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MASTER_ID");

                    b.ToTable("Masters");
                });

            modelBuilder.Entity("DiscogsContext.Models.Member", b =>
                {
                    b.Property<int>("ARTIST_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ARTIST_ID1")
                        .HasColumnType("int");

                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ARTIST_ID");

                    b.HasIndex("ARTIST_ID1");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("DiscogsContext.Models.Release", b =>
                {
                    b.Property<int>("RELEASE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("COUNTRY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DATA_QUALITY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IS_MAIN_RELEASE")
                        .HasColumnType("bit");

                    b.Property<int?>("MASTER_ID")
                        .HasColumnType("int");

                    b.Property<string>("NOTES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TITLE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RELEASE_ID");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("DiscogsContext.Models.Alias", b =>
                {
                    b.HasOne("DiscogsContext.Models.Artist", null)
                        .WithMany("ALIASES")
                        .HasForeignKey("ARTIST_ID1");
                });

            modelBuilder.Entity("DiscogsContext.Models.Group", b =>
                {
                    b.HasOne("DiscogsContext.Models.Artist", null)
                        .WithMany("GROUPS")
                        .HasForeignKey("ARTIST_ID1");
                });

            modelBuilder.Entity("DiscogsContext.Models.Image", b =>
                {
                    b.HasOne("DiscogsContext.Models.Artist", null)
                        .WithMany("IMAGES")
                        .HasForeignKey("ARTIST_ID");
                });

            modelBuilder.Entity("DiscogsContext.Models.Label", b =>
                {
                    b.HasOne("DiscogsContext.Models.Label+SubLabel", "PARENTLABEL")
                        .WithMany()
                        .HasForeignKey("PARENTLABELLABEL_ID");
                });

            modelBuilder.Entity("DiscogsContext.Models.Member", b =>
                {
                    b.HasOne("DiscogsContext.Models.Artist", null)
                        .WithMany("MEMBERS")
                        .HasForeignKey("ARTIST_ID1");
                });
#pragma warning restore 612, 618
        }
    }
}
